Updated terraform infra code for deploying nodejs app

diff --git a/pipelines/Jenkinsfile b/pipelines/Jenkinsfile
--- a/pipelines/Jenkinsfile
+++ b/pipelines/Jenkinsfile
@@ -35,29 +35,38 @@ pipeline {
                 ])
             }
         }
-        stage('Install Checkov') {
+        stage('Checkov Scan') {
             steps {
                 script {
-                    echo "Installing Checkov..."
-                    sh '''
-                        python3 -m venv venv  # Create virtual environment
-                        ./venv/bin/pip install --upgrade pip 
-                        ./venv/bin/pip install checkov 
-                    '''
-                }
-            }
-        }
+                    echo "Setting up Python virtual environment and installing Checkov..."
 
-        stage('Run Checkov') {
-            steps {
-                script {
-                    echo "Running Checkov security scan on Terraform files..."
-                    dir('GCP-CloudRun-Nodejs-Mysql-app') {
-                        sh './venv/bin/checkov -d .'
-                    }
-                }
-            }
+            // Create the virtual environment
+                    sh 'python3 -m venv venv'
+            
+            // Install pipx inside the virtual environment and ensure it's in PATH
+                    sh '''
+                        . venv/bin/activate  # Activate the virtual environment
+                        pip install --upgrade pip    # Upgrade pip to the latest version
+                        pip install checkov
+                    '''
+
+            // Verify the Checkov version
+                    sh '''
+                        . venv/bin/activate  # Activate the virtual environment again
+                        checkov --version            # Verify checkov installation
+                    '''
+
+            // Run Checkov scan with specific rules skipped
+                    sh '''
+                        . venv/bin/activate  # Ensure the virtual environment is activated
+                        echo "Current PATH: $PATH"  # Debug: print the PATH to check if venv is in the path
+                        which checkov  # Debug: print the location of checkov
+                        cd GCP-CloudRun-Nodejs-Mysql-infra
+                        checkov -d . --skip-check CKV_GCP_113,CKV_GCP_60 --output json --output-file checkov_report.json --quiet || (echo "Checkov scan failed!" && exit 1)
+                    '''
         }
+    }
+}
         stage('Terraform Init') {
             steps {
                 sh '''
@@ -86,5 +95,4 @@ pipeline {
         }
     }
 }
-
     
