Updated terraform infra code for deploying nodejs app

diff --git a/pipelines/Jenkinsfile b/pipelines/Jenkinsfile
--- a/pipelines/Jenkinsfile
+++ b/pipelines/Jenkinsfile
@@ -1,7 +1,6 @@
 pipeline {
     agent any
     environment {
-        PATH_TF = 'NodejsApp_GCP'
         TFACTION = "apply"
         GCP_PROJECT_ID = 'gcp-cloudrun-nodejs-mysql-app'      
         GCP_CREDENTIALS = credentials('gcp-service-account-key') 
@@ -36,21 +35,37 @@ pipeline {
                 ])
             }
         }
-        stage('Install dependencies') {
-            steps {
-                script {
-                    sh 'python3 -m venv venv'  
-                    sh './venv/bin/pip install --upgrade pip'  
-                    sh './venv/bin/pip install checkov'
-                }
-            }
-        }
         stage('Checkov Scan') {
             steps {
-                sh './venv/bin/checkov --version'
-                sh './venv/bin/checkov -d .  --skip-check CKV_GCP_113,CKV_GCP_60 --output json --output-file checkov_report.json --quiet || (echo "Checkov scan failed!" && exit 1)'
-            }
+                script {
+                    echo "Setting up Python virtual environment and installing Checkov..."
+
+            // Create the virtual environment
+                    sh 'python3 -m venv venv'
+            
+            // Install pipx inside the virtual environment and ensure it's in PATH
+                    sh '''
+                        . venv/bin/activate  # Activate the virtual environment
+                        pip install --upgrade pip    # Upgrade pip to the latest version
+                        pip install checkov
+                    '''
+
+            // Verify the Checkov version
+                    sh '''
+                        . venv/bin/activate  # Activate the virtual environment again
+                        checkov --version            # Verify checkov installation
+                    '''
+
+            // Run Checkov scan with specific rules skipped
+                    sh '''
+                        . venv/bin/activate  # Ensure the virtual environment is activated
+                        echo "Current PATH: $PATH"  # Debug: print the PATH to check if venv is in the path
+                        which checkov  # Debug: print the location of checkov
+                        checkov -d . GCP-CloudRun-Nodejs-Mysql-infra  --skip-check CKV_GCP_113,CKV_GCP_60 --output json --output-file checkov_report.json --quiet || (echo "Checkov scan failed!" && exit 1)
+                    '''
         }
+    }
+}
         stage('Terraform Init') {
             steps {
                 sh '''
